#A = int(input())
#B = int(input())
#C = int(input())
#D = int(input())
#dif = (A * B - C * D)
#print('DIFFERENCA = {}'.format(dif))

A = int(input())
B = int(input())
C = int(input())
D = int(input())
DIFERENCA = (A * B - C * D)
print('DIFERENCA = {}'.format(DIFERENCA))
